### PR TITLE
Fix linker errors when building for Android with IL2CPP

### PR DESCRIPTION
**Pull request by Snowblaze**

### CODE REVIEW

**Comment by KylinChang** [comment]
Thanks for the pull request. Will fix it in the next release.

**Comment by snorrsi** [comment]
> Thanks for the pull request. Will fix it in the next release.

Is the next release coming up soon?

As for now the Facebook SDK v7.16.0 can't be used for Android builds. I just updated and had to revert back to v7.15.1
Is there any workaround (except compiling it self) for getting it to work with Android?
Think you should at least mention that it's broken on the FacebookSDK Unity page.

**Comment by Snowblaze** [comment]
There is, you can just wrap the [DLLImport] with a UNITY_IOS directive and
every call of that function too.

**Comment by snorrsi** [comment]
> There is, you can just wrap the [DLLImport] with a UNITY_IOS directive and every call of that function too.

I know that, that's why I mentioned "except for compiling" it self. That is pretty obvious fix, just requires compiling.

Hope they will just soon release updated version that actually works for Android.

**Comment by Snowblaze** [comment]
Seems that you didn't notice the edit on my comment)

**Comment by KylinChang** [comment]
@snorrsi , we plan to release a new version this week.

**Comment by danoli3** [comment]
Thanks @KylinChang and @Snowblaze 👍

**Pull request closed without merging**
