### PR TITLE
Removes lag when sending FB Events from Unity

### PR DESCRIPTION
**Pull request by yershovlev**

### CODE REVIEW

**Comment by yershovlev** [comment]
Removes lag when sending FB Events from Unity. In some cases performance spikes can be critical and can drop FPS from 60 to 10, making this call asynchronous eliminates this problem.

**Comment by klgt** [comment]
I have experienced this issue in my Unity game, when will this pull request got merged?

**Comment by klgt** [comment]
@yershovlev could you build a release for your fix

**Comment by iquintero** [comment]
Hi @yershovlev thanks for contributing this. We will include it in the next release!

**Review by iquintero — APPROVED** [review]

**Pull request closed without merging**
