### PR TITLE
Android IL2CPP support.

### PR DESCRIPTION
**Pull request by bblpny**
These changes/removals allow IL2CPP android builds to be made without fatal link errors.

It seems Facebook intended to separate the P/Invoke code but did not get to it.

I've removed IOSWrapper.cs from the Facebook.Unity.dll module which is contained within IOSWrapper.cs in the Facebook.Unity.IOS.dll module.

I've replaced the call to new IOSWrapper() within the default constructor of IOSFacebook to the already existing GetIOSWrapper static method.

I've added a small piece of code that will attempt to find the type of IOSWrapper within the Facebook.Unity.IOS.dll module before manual loading of the assembly. Only because i've never seen any code that loads a assembly in this manor in regards to unity (which should load all assemblies at start up). In the case of initialization race conditions I left the call to load the assembly as is when System.Type.GetType fails.

All of this is untested. IOSWrapper's constructor and or class may need to be marked with Preserve attributes in iOS IL2CPP targets.

### CODE REVIEW

**Comment by bblpny** [comment]
I signed it facebook-github-bot . thanks

**Comment by bblpny** [comment]
I've made an additional change. IL2CPP rarely succeeds at heavy usage of reflection such as in AndroidWrapper. The wrapping of UnityEngine.AndroidJavaClass causes a fatal crash as noted in issues. 

I do not fully understand the reasoning to wrapping AndroidJavaClass with reflection and i'm not questioning there was a reason to but it doesn't work on IL2CPP so I replaced it with direct function calls. I am unaware of AndroidJavaClass / AndroidJavaObject introducing build failures when referenced outside of android for any platform.

Also, a little off topic, but it seems the Facebook.Unity.iOS source code is not on github.

**Comment by PimDeWitte** [comment]
@bblpny it looks like Facebook asks in their repo documentation to submit PRs to their dev branch, maybe that is why this hasn't been merged yet.

**Comment by swiese** [comment]
Il2cpp for Android should work in 7.9.0

**Pull request closed without merging**
